jobs:
  - name: workflow-orchestration-poc-pr
    plan:
      - get: workflow-orchestration-poc-pr
        trigger: true
        version: every
      - put: workflow-orchestration-poc-pr
        params:
          path: workflow-orchestration-poc-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          workflow-orchestration-poc: workflow-orchestration-poc-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          workflow-orchestration-poc: workflow-orchestration-poc-pr
        params:
          TF_WORKSPACE: "qa"
          DETAILED_EXITCODE: ""
        on_failure:
          put: workflow-orchestration-poc-pr
          params:
            path: workflow-orchestration-poc-pr
            status: failure
        on_success:
          put: workflow-orchestration-poc-pr
          params:
            path: workflow-orchestration-poc-pr
            status: success
